### ISSUE TITLE
TypeError: Connot read property 'buffer' of null

### ISSUE THREAD

**Issue by FlorentMasson** [kspearrin/ff-password-exporter#1]
Doesn't work, I get a popup "TypeError: Connot read property 'buffer' of null" when I try to export
Firefox 59.0.3 (64 bits) on Windows7

**Comment by kspearrin** [comment]
Does your Firefox profile folder have a key4.db file?

**Comment by linuxnow** [comment]
Same happens to me. I have a key4.db file. I have tried stopping firefox, just in case it was a lock problem, but the error is still happening.

**Comment by FlorentMasson** [comment]
I have a key4.db too.
I suceeded using passwordfox instead with the command line option to
specify the master password.

2018-05-25 12:02 GMT+02:00 Pau Aliagas <notifications@github.com>:

**Comment by linuxnow** [comment]
Works!

**Comment by kspearrin** [comment]
I pushed out v1.0.1
