### ISSUE TITLE
[feature request] add date columns to export

### ISSUE THREAD

**Issue by mokkin** [kspearrin/ff-password-exporter#15]
It would be nice to add the date columns "last used" and "last changed" to export.
Then it can be easily imported with correct dates in third party applications like nextcloud passwords.

**Comment by kspearrin** [comment]
They are there: https://github.com/kspearrin/ff-password-exporter/blob/master/src/renderer.js#L152

Update just hasn't been released yet.

**Comment by mokkin** [comment]
That's cool!
I tried with the master and it worked like charm.
Thanks again!

**Comment by mokkin** [comment]
Okay, I didn't know this format and I converted them into standard format.
I close this here. A conversion function should be worth a separate ticket, if needed.
