### ISSUE TITLE
cannot get ff-pasword-exporter to install and run on Ubuntu 18.04.1 with current instructions.s

### ISSUE THREAD

**Issue by LuigiWriter** [kspearrin/ff-password-exporter#29]
All I want to do is get my wife's and my several hundred passwords out of Firefox and into Opera.

 After adding Bitwarden to Firefox I find out It can't get any out of Firefox without a .csv file that ff-password-exporter is supposed to be so-easily installed and then produce. 

When I down load 
Linux

    Portable (.AppImage, x64)

I get 

![selection_002](https://user-images.githubusercontent.com/30986842/53624083-fd447500-3bcc-11e9-8ab0-db743c8bb6c7.png)
if I select disk image mounter I get

![selection_003](https://user-images.githubusercontent.com/30986842/53624122-2533d880-3bcd-11e9-85cf-d2e85a9c84db.png)

If I click [open link]
I get

![selection_004](https://user-images.githubusercontent.com/30986842/53624154-43013d80-3bcd-11e9-95c5-6aec5de087ab.png)

When I run npm I get this.
anne@anne-110-220z:~$ npm run electron
npm ERR! Linux 4.18.0-15-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "electron"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/anne/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/anne/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/anne/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anne/npm-debug.log
anne@anne-110-220z:~$ 

The debug log is here
[npm-debug.log](https://github.com/kspearrin/ff-password-exporter/files/2918463/npm-debug.log)

There are more than 20 package.json files, but none are in 
/home/anne/

and none of the sub directories of /home/anne/
contain any reference to npm or ff-password-exporter.

Essentially once the readme says download and install I am left on my own with no guidance 
* of where the appimage is supposed to go
   - Do I just save it
      * That does not create this package.json than npm is looking for
   - Do I use the disk image mounter
      * If so what application do I really use to process the "Appimage application bundle" 
      * Is there one that will produce this package.json file for npm to find?
* of how to run the appimage with npm, 
* or how this package.json is is supposed to get into /home/anne/

I searched in ask.ubuntu, with google on line, and not a mention of how to do this anywhere, 

Copy and pasting user names and pass words one at a time from one window to another window is going to be tedious and error prone. And on this two year old machine take hours of waiting for the two CPU's to drop below 100% with more than one window of Firefox open or both Firefox and Opera open.  Only about 5% of the 16 Gb of RAM is even getting touched.

I hope someone knows how to do this on a Linux OP Sys; can write it down and share it.
Please!
Luigi

**Comment by kspearrin** [comment]
You need to make the .AppImage executable, then just click it.

**Comment by LuigiWriter** [comment]
Oh what a #$%^& Windows Hangover. 
Most basic thing I like about Linux / Unix. Thanks for pointing out what should have been casual to this obvious observer. 
Thanks, and thanks again.
Spent hours. Definitely failing my Old Geek exam.
To think I used to be the one giving one line solutions [that worked] for someone's hours of distress back in the 8- and 16-bit days.
