### ISSUE TITLE
Dev instructions in the readme fail: "missing script electron"

### ISSUE THREAD

**Issue by sakoht** [kspearrin/ff-password-exporter#38]
I cloned the repo and attempted the follow the dev instructions:
```
npm install
npm run electron
```

I get this error from `npm run electron`:
```
> npm run electron
npm ERR! missing script: electron

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ssmith/.npm/_logs/2019-11-30T18_59_57_939Z-debug.log
```

Possibly the build/run process has been updated but the README is behind?

**Comment by kspearrin** [comment]
This is still the correct process for running the app. Make sure you are in the root directory of the project.
