### ISSUE TITLE
Exporting doesn't work (TypeError: str.charCodeAt is not a function)

### ISSUE THREAD

**Issue by taylankasap** [kspearrin/ff-password-exporter#41]
Not many steps to reproduce:

1. Run the program
2. Correct profile is already detected & selected (there is only one)
3. Enter the master password
4. Click **Export Passwords**
5. Error popup: TypeError: str.charCodeAt is not a function

Tried (all same error):

- Removing master password
- Running the program as admin
- Portable & installable versions
- Building from source with dist:win and running the win-unpacked\FF Password Exporter.exe
- Building from source with dist:win:ci and running the win-unpacked\FF Password Exporter.exe

Other info:

- Firefox Developer Edition 73.0b6 (64-bit)
- Windows 10 Insider Build 19041.21
- Profile path doesn't have any special characters (not even a space).
- I have passwords saved on some domains that point to localhost and different ports (if related at all).
- When I use `showAlert('error', JSON.stringify(item2Asn1));` just before renderer.js:202 it shows like this:
![image](https://user-images.githubusercontent.com/4192479/72622675-c4cc9780-3954-11ea-9b50-5cd14b4e7083.png)
    - Looks like recursion to me (probably because it's an object and I'm trying to debug it with JSON.stringify).
    - What is going on with the last part (weird characters)?

Sorry, I can't debug properly because I'm using docker on WSL and don't know how to set up X Server yet. So I'm building and running it on Windows instead of using `npm run electron`.

**Comment by taylankasap** [comment]
Okay, I set up the XServer. Now I can run/debug the app directly via electron.

Basically renderer.js:200 thinks it gets a string but it gets an array. I don't know anything about forge package so please direct me to help you debug it if you can't reproduce.

This is the output of `console.log('item2Asn1', item2Asn1);`
![image](https://user-images.githubusercontent.com/4192479/72653950-6c21ec80-399e-11ea-9816-9dbaa95354ab.png)

**Comment by Spielmops** [comment]
I confirm that error with Firefox 72 on Linux.Thats new, because the exporter worked with FF 70 ..

Spielmops

**Comment by took** [comment]
I confirm that error with Firefox 73 on Linux.

**Comment by Cairo2k18** [comment]
Getting this error on Windows 7 Ultimate, Firefox 73.0.1 (x64)

**Comment by took** [comment]
The structure of item2Asn1 seem to be different in older ff versions. With this, I do not get the "TypeError: str.charCodeAt is not a function" Error any more.

`const item2Salt = item2Asn1.value[0].value[0].value; // + item2Asn1.value[0].value[1].value[0].value[1].value[0].value;
const item2Data = item2Asn1.value[1].value;`

Sadly the values seem not to be the ones we are looking for since I now always get "Master password incorrect." (because item2Value.data is not equal to 'password-check').

**Comment by Pyrross** [comment]
Same on MacOS.

**Comment by mimmoz81** [comment]
same here on Windows 10, FF 74

**Comment by GeryEmreis** [comment]
In FF 73, they changed algorithm from 3DES to AES https://phabricator.services.mozilla.com/rNSSfc636973ad06392d11597620b602779b4af312f6

**Comment by DAC324** [comment]
Looks like the decryption functions need to be adapted as the database items are now encrypted using AES256 instead of 3DES / ASN1. 
This means that at least the calls to forge.asn1.fromDer() need to be replaced by the AES256 equivalent. 
Unfortunately, I am neither a node.js nor a crypto expert and reading through the node.js and forge documentation, I was not able to identify an appropriate solution.

**Comment by pwintermeyer** [comment]
weirdly, on one machine running windows 10 and 73.0.1, I do not get the error

but if I create a profile on a machine running Version 74, and then sync it with a new profile on the computer running version 73.0.1, the error follows the data

the original profile on the version 73.0.1 machine works ok

**Comment by sisyphosloughs** [comment]
I can confirm the bug for FF 74.0.1@macOS 10.15.3 (19D76)

**Comment by markran** [comment]
Confirming bug for FF 75.0 @Win10 x64. :-(

**Comment by coalpha** [comment]
I can confirm for FF 76.0b3 (64-bit) on Windows 10 x64

**Comment by keddad** [comment]
Same thing on Firefox 75.0 running Manjaro Linux :(

**Comment by desgnu** [comment]
Same here

**Comment by Oscar7601** [comment]
Same issue for me.

**Comment by juliennicouleaud** [comment]
Same here on macOS Catalina 10.15.3 and 10.15.4, Firefox 75.0.

**Comment by lmateovf** [comment]
Same here on macOS Catalina

What a pitty, I used to love this tool!

**Comment by israuor** [comment]
Same here using firefox 76 on archlinux

**Comment by zfogg** [comment]
+1

**Comment by desgnu** [comment]
An Idea I would recommned looking into, since obvious it's worked and is likely been borked due to an update with out firefox handels password storage. Maybe try snooping on however other non-firefox browsers import passwords from firefox?

**Comment by mnoorenberghe** [comment]
See https://github.com/kspearrin/ff-password-exporter/issues/41#issuecomment-607704526 and firepwd's fix

**Comment by kspearrin** [comment]
@mnoorenberghe Can you link to firepwd's fix?

**Comment by mnoorenberghe** [comment]
There are multiple commits but the main ones are:
* https://github.com/lclevy/firepwd/commit/4981e8dd4cc29ea05bcb2eb36d78d3113b207834
* https://github.com/lclevy/firepwd/commit/31a6abc07705652a43fa5e0d9a3bfd702ff26cac

**Comment by eugene-bodrov** [comment]
+1 (W10, FF 76.0.1(x64), Firefox Lockwise)

**Comment by mnoorenberghe** [comment]
This is a duplicate of #50 which has a fix now.

**Comment by kspearrin** [comment]
Fixed in v1.2.0 that was just released.
