### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by hati39** [kspearrin/ff-password-exporter#5]
FF v60.0.1
I've got the following error
![error](https://user-images.githubusercontent.com/20671798/40896856-eb9e6b60-67b7-11e8-9c07-4800d123ea7f.jpg)

**Comment by dgorbash** [comment]
Possibly duplicate of #1. 
It seems binary releases isn't updated yet.

Did you tried to run it from sources?

**Comment by hati39** [comment]
oh, didn't realize that, thanks. However, my workaround was to import to Chrome, import to RoboForm, export to csv. Have to sleep, will try later and leave the case open until me or s/o else checks this

**Comment by hati39** [comment]
ok, couldn't wait ;) Fix works.

**Comment by kspearrin** [comment]
I pushed out v1.0.1
