### ISSUE TITLE
TypeError: str.charCodeAt is not a function

### ISSUE THREAD

**Issue by ClaGugliotta** [kspearrin/ff-password-exporter#50]
I try to run the application, but i receive this error. any solution ?

**Comment by cryptism** [comment]
If anyone's curious, Firefox has recently moved to PBES2 encryption, which has changed the certificate structure.

I should have a PR to fix this soon.

**Comment by mnoorenberghe** [comment]
Note that [export to CSV is built into](https://www.ghacks.net/2020/05/31/firefox-may-soon-get-native-password-exports/) [Firefox Nightly 79](https://nightly.mozilla.org). You can copy your logins.json and key4.db to a Nightly Firefox profile to export.

**Comment by cryptism** [comment]
Great, that's my evening wasted :weary:

**Comment by mnoorenberghe** [comment]
Well it won't be released for 8 weeks to the general public so I don't think it's a total waste.

**Comment by cryptism** [comment]
I see. Fair enough, will keep at it then

**Comment by cryptism** [comment]
Fix now awaiting some love from @kspearrin #51 

If anyone wants to try this out, feel free to build from my repo: https://github.com/cryptism/ff-password-exporter
