### ISSUE TITLE
1.2 still doesn't work

### ISSUE THREAD

**Issue by SteenG** [kspearrin/ff-password-exporter#53]
I get this error: Too few bytes to read ASN.1 value.

**Comment by cryptism** [comment]
Yes, the fix won't be for the issue you're seeing, sorry. I'm having a tough time recreating your bug, but it's possibly related to: https://bugzilla.mozilla.org/show_bug.cgi?id=1064670

@SteenG Are you comfortable with building and running code with `npm`? Let me know if so, I'd quite like you to test something out.

**Comment by cryptism** [comment]
Regardless, if anyone else has this problem, https://github.com/cryptism/ff-password-exporter has a patch which I suspect may fix this, and it would be greatly appreciated if anyone who has this issue could confirm to me whether they can successfully extract their passwords running from my fork.

**Comment by kspearrin** [comment]
Duplicate https://github.com/kspearrin/ff-password-exporter/issues/17 . Please let me know if the fix by @cryptism works or not and we can merge it in.
