### ISSUE TITLE
There is a lot of garbled text in the csv file.

### ISSUE THREAD

**Issue by Pikemo** [kspearrin/ff-password-exporter#9]
@kspearrin Hello. There is a lot of garbled text in the csv file.

Windows 10 version 1803
Firefox Nightly 62.0a1 64-Bit
Language: Chinese (Traditional)

<details open=""><summary>Screenshot</summary>
<p><a href="https://user-images.githubusercontent.com/22120513/41757217-3987c092-7613-11e8-8654-ab3816cef8cb.png" rel="nofollow"><img src="https://user-images.githubusercontent.com/22120513/41757217-3987c092-7613-11e8-8654-ab3816cef8cb.png" alt="image" style="max-width:100%;"></a></p>
</details>

**Comment by kspearrin** [comment]
Not sure. Maybe you need to set the encoding to UTF-8?

**Comment by PoLaKoSz** [comment]
I fixed my similar problem (You can [find the solution here](https://github.com/kspearrin/ff-password-exporter/issues/10)) but try with different ecoding.
